/** Canonical Mwendo Salama domain types. */
export type UserRole = 'passenger' | 'sacco_manager' | 'authority' | 'admin';
export interface UserClaims { activeRole?: UserRole | undefined; saccoId?: string | undefined; authorityScope?: 'national' | 'county' | undefined; isSuspended?: boolean | undefined; mfaVerifiedAt?: number | undefined; [key: string]: unknown; }
export interface UserProfile { id:string; uid:string; email:string; displayName:string; phoneNumber?:string | undefined; role:UserRole; activeRole?:UserRole | undefined; claimedActiveRole?:UserRole | undefined; claimedSaccoId?:string | undefined; claimedAuthorityScope?:'national'|'county' | undefined; claimedIsSuspended?:boolean | undefined; claims?:UserClaims | undefined; saccoId?:string | undefined; authorityId?:string | undefined; authorityScope?:'national'|'county' | undefined; county?:string | undefined; badgeNumber?:string | undefined; isVerified:boolean; isActive:boolean; isMfaEnrolled?:boolean | undefined; isMfaVerified?:boolean | undefined; mfaVerifiedAt?:number | undefined; isAnonymous?:boolean | undefined; trustScore?:number | undefined; trustBadge?:'bronze'|'silver'|'gold'|'verified_guardian' | undefined; safetyPoints?:number | undefined; rewardTier?:'Bronze'|'Silver'|'Gold' | undefined; pointsHistory?:Array<{event:string;points:number;timestamp:string}> | undefined; termsAccepted?:boolean | undefined; privacyPolicyVersion?:string | undefined; termsAcceptedAt?:string | undefined; ageConfirmed?:boolean | undefined; ageConfirmedAt?:string | undefined; analyticsConsent?:boolean | undefined; analyticsConsentAt?:string | undefined; emergencyContacts?:Array<{name:string;phone:string;relationship:string}> | undefined; language?:'en'|'sw' | undefined; theme?:'light'|'dark'|'system' | undefined; notificationPreferences?:{overspeedAlerts:boolean;blackspotWarnings:boolean;weeklyDigest:boolean} | undefined; createdAt:string; updatedAt:string; }
export interface SharedTrip { id:string; tripId:string; plateNumber:string; saccoName:string; routeName:string; status:'active'|'completed'|'paused'; safetyStatus:string; currentSpeedKmH:number; maxSpeedKmH:number; overspeedEventsCount:number; lastUpdatedAt:string; expiresAt:string; }
export type TripStatus='active'|'completed'|'auto_completed'|'incomplete_signal_lost'|'discarded';
import type { Timestamp } from 'firebase/firestore';
export interface GPSPoint { latitude:number; longitude:number; speedKmH:number; accuracy?:number | undefined; timestamp:Timestamp|string; heading?:number | undefined; }
export interface Trip { id:string; tripId?:string | undefined; vehicleId?:string | undefined; isProvisional?:boolean | undefined; vehicleRegNumber:string; plateNumber?:string | undefined; saccoId:string; saccoName:string; routeName:string; origin?:string | undefined; destination?:string | undefined; status:TripStatus; currentSpeedKmH:number; maxSpeedKmH:number; avgSpeedKmH:number; driverName?:string | undefined; passengerCount?:number | undefined; startTime:Timestamp|string; endTime?:Timestamp|string | undefined; durationSeconds?:number | undefined; distanceMeters?:number | undefined; overspeedEventsCount?:number | undefined; violationsCount?:number | undefined; userId?:string | undefined; startLocation?:{latitude:number;longitude:number;geohash?:string | undefined} | undefined; endLocation?:{latitude:number;longitude:number;geohash?:string | undefined} | undefined; lastGpsUpdate?:GPSPoint | undefined; telemetryStoragePath?:string | undefined; traceId?:string | undefined; timestamp?:Timestamp|string | undefined; createdAt?:Timestamp|string | undefined; updatedAt?:Timestamp|string | undefined; retryCount?:number | undefined; }
export interface Vehicle { id:string; regNumber:string; saccoId:string; saccoName:string; capacity:number; status:'active'|'maintenance'|'suspended'; insuranceExpiry:string; inspectionExpiry:string; riskScore?:number | undefined; riskTier?:'low'|'medium'|'high'|'critical' | undefined; isProvisional?:boolean | undefined; }
export interface VehiclePublicSummary { id:string; vehicleId?:string | undefined; regNumber:string; saccoId:string; saccoName:string; capacity?:number | undefined; status?:'active'|'maintenance'|'suspended' | undefined; riskScore?:number | undefined; riskTier?:'low'|'medium'|'high'|'critical' | undefined; isProvisional?:boolean | undefined; updatedAt?:string | undefined; }
export interface SACCO { id:string; name:string; registrationCode:string; fleetCount:number; safetyScore:number; contactPhone:string; contactEmail:string; status:'active'|'under_review'|'suspended'; }
export type SeverityLevel='low'|'medium'|'high'|'critical'; export type HazardType='accident_prone'|'pothole'|'carjacking_risk'|'poor_lighting'|'unmarked_bump'|'police_checkpoint'|'flash_flooding';
export interface BlackSpot { id:string; spotId?:string | undefined; name:string; title?:string | undefined; routeName:string; county?:string | undefined; latitude:number; longitude:number; radiusMeters?:number | undefined; severity:SeverityLevel; hazardType?:HazardType | undefined; accidentCount12M?:number | undefined; hazardDescription:string; description?:string | undefined; reportedByUid:string; verifiedByAuthority?:boolean | undefined; corroborationCount?:number | undefined; corroborationsCount?:number | undefined; confidenceScore?:number | undefined; reporterTrustScore?:number | undefined; evidencePhotoUrls?:string[] | undefined; status?:'pending'|'published'|'under_review'|'rejected'|'archived'|'resolved' | undefined; stillThereCount?:number | undefined; resolvedCount?:number | undefined; lastConfirmedAt?:string | undefined; lastReportedAt?:string | undefined; createdAt:string; updatedAt?:string | undefined; retryCount?:number | undefined; }
export interface BlackSpotReport { id?:string; reportId?:string; spotId:string; reportedByUid:string; reportedByDisplayName?:string; title?:string; description?:string; hazardType?:HazardType|string; severity?:SeverityLevel; location:{ lat:number; lng:number }; latitude:number; longitude:number; photoUrl?:string; reporterTrustScore?:number; createdAt:string; }
export interface BlackSpotConfirmation { id?:string; userId:string; type:'still_there'|'resolved'; timestamp:Timestamp|string; createdAt?:string; }
export interface TripViolationSummary { type:string; speed?:number; location?:string; details?:string; }
export interface GenerateTripSummaryPayload { tripId?:string; maxSpeedKmH:number; avgSpeedKmH?:number; durationSeconds?:number; saccoName?:string; routeName?:string; overspeedEventsCount?:number; violations?:TripViolationSummary[]; }
export interface GenerateTripSummaryResult { success:boolean; summary:string; riskTier:'low'|'moderate'|'high'; overspeedEventsCount:number; generatedBy:'gemini'|'rule_engine'; }
export type AlertType='overspeeding'|'blackspot_approaching'|'harsh_braking'|'sos'|'route_deviation'; export interface SafetyAlert { id:string; tripId:string; userId?:string | undefined; vehicleRegNumber:string; driverName?:string | undefined; saccoId:string; type:AlertType; severity:SeverityLevel; message:string; latitude:number; longitude:number; speedKmH:number; timestamp:string; acknowledgedBySacco?:boolean | undefined; acknowledgedByAuthority?:boolean | undefined; status?:'active'|'resolved'|'cancelled' | undefined; }
export interface PlatformAnalyticsDaily { id:string;docId?:string | undefined;date:string;type:'daily'|'platform_daily';totalTrips:number;totalViolations:number;activeAlerts:number;riskDistribution:{low:number;medium:number;high:number;critical:number};userCount?:number | undefined;saccoCount?:number | undefined;auditLogCount?:number | undefined;complaintCount?:number | undefined;updatedAt:string; }
export interface SaccoAnalyticsDaily { id:string;docId?:string | undefined;saccoId:string;type:'sacco'|'sacco_daily';safetyScore:number;fleetCount:number;unresolvedComplaints:number;updatedAt:string; } export type AnalyticsDocument=PlatformAnalyticsDaily|SaccoAnalyticsDaily;
export interface Driver { id:string;name:string;licenseNumber:string;saccoId:string;assignedVehicleReg?:string | undefined;routeName?:string | undefined;status:'active'|'on_leave'|'suspended';safetyScore:number;phone?:string | undefined;totalTrips?:number | undefined;totalViolations?:number | undefined;createdAt?:string | undefined; }
export interface Violation { id:string;violationId?:string | undefined;saccoId:string;userId?:string | undefined;vehicleRegNumber:string;driverName?:string | undefined;routeName?:string | undefined;recordedSpeedKmH:number;speedLimitKmH:number;severity:SeverityLevel;confidenceScore:number;isCorroborated:boolean;timestamp:Timestamp|string;status:'pending'|'reviewed'|'disputed'|'dismissed';locationName?:string | undefined;latitude?:number | undefined;longitude?:number | undefined;createdAt?:Timestamp|string | undefined;updatedAt?:Timestamp|string | undefined; }
export interface Complaint { id:string;saccoId:string;vehicleRegNumber?:string | undefined;passengerName?:string | undefined;reportedByUid?:string | undefined;title:string;description:string;status:'open'|'investigating'|'resolved';createdAt:string; }
export interface AuditLog { id:string;saccoId:string;actorName:string;actorRole:string;action:string;target:string;timestamp:string; }
export interface TeamUser { id:string;saccoId:string;name:string;email:string;role:'sacco_manager'|'operations'|'viewer';status:'active'|'invited'|'suspended';lastActive?:string | undefined; }
export interface InspectionReport { id:string;vehicleRegNumber:string;saccoId:string;saccoName?:string | undefined;inspectorId:string;inspectorName:string;county:string;inspectionDate:string;speedGovernorStatus:'valid'|'tampered'|'expired'|'missing';brakeStatus:'pass'|'fail';tireStatus:'pass'|'fail';overallResult:'passed'|'failed'|'impounded'|'suspended';certificateNumber?:string | undefined;expiryDate?:string | undefined;notes?:string | undefined;createdAt:string; }
export interface UserRateLimitDoc { id:string;userId:string;sosTimestamps?:number[] | undefined;blackSpotTimestamps?:number[] | undefined;updatedAt:string; }
