import {
  SACCO,
  Vehicle,
  VehiclePublicSummary,
  BlackSpot,
  SafetyAlert,
  Driver,
  Violation,
  Complaint,
  AuditLog,
  TeamUser,
  InspectionReport,
  Trip,
  PlatformAnalyticsDaily,
} from '../types';

export const MOCK_SACCOS: SACCO[] = [
  {
    id: 'sacco_metrolink',
    name: 'MetroLink SACCO',
    registrationCode: 'SACCO-NRB-042',
    fleetCount: 85,
    safetyScore: 92,
    contactPhone: '+254 711 200 300',
    contactEmail: 'ops@metrolink.co.ke',
    status: 'active',
  },
  {
    id: 'sacco_2nk',
    name: '2NK Sacco',
    registrationCode: 'SACCO-NYR-011',
    fleetCount: 140,
    safetyScore: 95,
    contactPhone: '+254 722 300 400',
    contactEmail: 'safety@2nksacco.co.ke',
    status: 'active',
  },
  {
    id: 'sacco_metro',
    name: 'Super Metro SACCO',
    registrationCode: 'SACCO-NRB-088',
    fleetCount: 190,
    safetyScore: 96,
    contactPhone: '+254 733 400 500',
    contactEmail: 'control@supermetro.co.ke',
    status: 'active',
  },
  {
    id: 'sacco_greenline',
    name: 'GreenLine SACCO',
    registrationCode: 'SACCO-NKR-023',
    fleetCount: 65,
    safetyScore: 89,
    contactPhone: '+254 700 500 600',
    contactEmail: 'support@greenline.co.ke',
    status: 'active',
  },
  {
    id: 'sacco_transitstar',
    name: 'TransitStar SACCO',
    registrationCode: 'SACCO-MSA-005',
    fleetCount: 52,
    safetyScore: 87,
    contactPhone: '+254 720 600 700',
    contactEmail: 'admin@transitstar.co.ke',
    status: 'active',
  },
  {
    id: 'sacco_cityride',
    name: 'CityRide SACCO',
    registrationCode: 'SACCO-NRB-104',
    fleetCount: 44,
    safetyScore: 90,
    contactPhone: '+254 710 800 900',
    contactEmail: 'fleet@cityride.co.ke',
    status: 'active',
  },
];

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: 'KBZ819M',
    regNumber: 'KBZ 819M',
    saccoId: 'sacco_2nk',
    saccoName: '2NK Sacco',
    capacity: 14,
    status: 'active',
    insuranceExpiry: '2027-01-15',
    inspectionExpiry: '2027-03-20',
    riskScore: 94,
    riskTier: 'low',
    isProvisional: false,
  },
  {
    id: 'KCA123X',
    regNumber: 'KCA 123X',
    saccoId: 'sacco_metro',
    saccoName: 'Super Metro SACCO',
    capacity: 33,
    status: 'active',
    insuranceExpiry: '2026-11-30',
    inspectionExpiry: '2026-12-15',
    riskScore: 96,
    riskTier: 'low',
    isProvisional: false,
  },
  {
    id: 'KDD456Y',
    regNumber: 'KDD 456Y',
    saccoId: 'sacco_metrolink',
    saccoName: 'MetroLink SACCO',
    capacity: 33,
    status: 'active',
    insuranceExpiry: '2026-10-10',
    inspectionExpiry: '2026-11-05',
    riskScore: 78,
    riskTier: 'medium',
    isProvisional: false,
  },
  {
    id: 'KDB789Z',
    regNumber: 'KDB 789Z',
    saccoId: 'sacco_greenline',
    saccoName: 'GreenLine SACCO',
    capacity: 14,
    status: 'active',
    insuranceExpiry: '2027-02-14',
    inspectionExpiry: '2027-04-01',
    riskScore: 91,
    riskTier: 'low',
    isProvisional: false,
  },
  {
    id: 'KDA992B',
    regNumber: 'KDA 992B',
    saccoId: 'sacco_transitstar',
    saccoName: 'TransitStar SACCO',
    capacity: 44,
    status: 'active',
    insuranceExpiry: '2026-09-25',
    inspectionExpiry: '2026-10-30',
    riskScore: 72,
    riskTier: 'medium',
    isProvisional: false,
  },
  {
    id: 'KCW304R',
    regNumber: 'KCW 304R',
    saccoId: 'sacco_cityride',
    saccoName: 'CityRide SACCO',
    capacity: 25,
    status: 'active',
    insuranceExpiry: '2026-12-20',
    inspectionExpiry: '2027-01-10',
    riskScore: 88,
    riskTier: 'low',
    isProvisional: false,
  },
  {
    id: 'KCC512F',
    regNumber: 'KCC 512F',
    saccoId: 'sacco_2nk',
    saccoName: '2NK Sacco',
    capacity: 14,
    status: 'maintenance',
    insuranceExpiry: '2026-08-01',
    inspectionExpiry: '2026-08-15',
    riskScore: 54,
    riskTier: 'high',
    isProvisional: false,
  },
];

export const MOCK_VEHICLE_SUMMARIES: VehiclePublicSummary[] = MOCK_VEHICLES.map((v) => ({
  id: v.id,
  vehicleId: v.id,
  regNumber: v.regNumber,
  saccoId: v.saccoId,
  saccoName: v.saccoName,
  capacity: v.capacity,
  status: v.status,
  riskScore: v.riskScore,
  riskTier: v.riskTier,
  isProvisional: v.isProvisional,
  updatedAt: new Date().toISOString(),
}));

export const MOCK_PUBLIC_PINS = [
  {
    id: 'pin_salgaa',
    title: 'Salgaa Black Spot Corridor',
    routeName: 'Nakuru - Eldoret Highway (A104)',
    locationName: 'Salgaa Descent',
    latitude: -0.2173,
    longitude: 35.8569,
    severity: 'critical',
    type: 'blackspot',
    corroborationCount: 42,
    description: 'Steep downhill gradient with high heavy-goods vehicle density. Frequent brake failures and head-on collisions reported.',
  },
  {
    id: 'pin_sachangwan',
    title: 'Sachangwan Sharp Curves',
    routeName: 'Nakuru - Eldoret Highway',
    locationName: 'Sachangwan Section',
    latitude: -0.1833,
    longitude: 35.7833,
    severity: 'critical',
    type: 'blackspot',
    corroborationCount: 38,
    description: 'Dangerous road descent, blind corners, and high risk during wet weather.',
  },
  {
    id: 'pin_kinungi',
    title: 'Kinungi Escarpment Stretch',
    routeName: 'Nairobi - Naivasha Highway',
    locationName: 'Kinungi / Fly Over',
    latitude: -0.7933,
    longitude: 36.5681,
    severity: 'high',
    type: 'blackspot',
    corroborationCount: 29,
    description: 'High-speed overtaking zone with sudden pedestrian crossings and poor night visibility.',
  },
  {
    id: 'pin_kamandura',
    title: 'Kamandura Mai Mahiu Junction',
    routeName: 'Limuru - Mai Mahiu Road',
    locationName: 'Kamandura Corner',
    latitude: -1.1644,
    longitude: 36.6389,
    severity: 'high',
    type: 'blackspot',
    corroborationCount: 21,
    description: 'Dense morning fog and sharp descending bends along the Rift Valley escarpment.',
  },
  {
    id: 'pin_kibarani',
    title: 'Kibarani Causeway Bend',
    routeName: 'Mombasa - Nairobi Highway (A109)',
    locationName: 'Kibarani Changamwe',
    latitude: -4.0415,
    longitude: 39.6382,
    severity: 'medium',
    type: 'blackspot',
    corroborationCount: 16,
    description: 'Sharp curved causeway approaching Makupa bridge, frequent oil slicks and container traffic.',
  },
  {
    id: 'pin_ngata',
    title: 'Ngata Bridge Descent',
    routeName: 'Nakuru - Salgaa Highway',
    locationName: 'Ngata Bridge',
    latitude: -0.2520,
    longitude: 35.9810,
    severity: 'high',
    type: 'blackspot',
    corroborationCount: 24,
    description: 'Narrow river bridge situated immediately after a steep continuous gradient.',
  },
  {
    id: 'pin_knh',
    title: 'Kenyatta National Hospital Trauma Center',
    routeName: 'Hospital Road, Nairobi',
    locationName: 'KNH Emergency Wing',
    latitude: -1.3013,
    longitude: 36.8073,
    severity: 'low',
    type: 'hospital',
    corroborationCount: 50,
    description: 'Level 6 National Referral Hospital equipped with dedicated trauma and emergency intensive care.',
  },
  {
    id: 'pin_salgaa_police',
    title: 'Salgaa Highway Police Base',
    routeName: 'Eldoret - Nakuru Highway',
    locationName: 'Salgaa Police Post',
    latitude: -0.2150,
    longitude: 35.8520,
    severity: 'low',
    type: 'police',
    corroborationCount: 30,
    description: 'NTSA and National Police Service highway patrol rapid response station.',
  },
];

export const MOCK_BLACK_SPOTS: BlackSpot[] = MOCK_PUBLIC_PINS.filter((p) => p.type === 'blackspot').map((p) => ({
  id: p.id,
  spotId: p.id,
  name: p.title,
  title: p.title,
  routeName: p.routeName,
  county: p.locationName.includes('Mombasa') ? 'Mombasa' : p.locationName.includes('Nairobi') ? 'Nairobi' : 'Nakuru',
  latitude: p.latitude,
  longitude: p.longitude,
  radiusMeters: 250,
  severity: p.severity as 'critical' | 'high' | 'medium' | 'low',
  hazardType: 'accident_prone',
  accidentCount12M: p.corroborationCount,
  hazardDescription: p.description,
  description: p.description,
  reportedByUid: 'demo_authority_user',
  verifiedByAuthority: true,
  corroborationCount: p.corroborationCount,
  confidenceScore: 92,
  status: 'published',
  createdAt: '2026-01-10T08:00:00.000Z',
  updatedAt: new Date().toISOString(),
}));

export const MOCK_SAFETY_ALERTS: SafetyAlert[] = [
  {
    id: 'alert_001',
    tripId: 'trip_demo_101',
    vehicleRegNumber: 'KBZ 819M',
    driverName: 'John Mwangi',
    saccoId: 'sacco_2nk',
    type: 'blackspot_approaching',
    severity: 'high',
    message: 'Caution: Approaching Kinungi Black Spot zone. Reduce speed to under 60 km/h.',
    latitude: -0.7933,
    longitude: 36.5681,
    speedKmH: 74,
    timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    status: 'active',
  },
  {
    id: 'alert_002',
    tripId: 'trip_demo_102',
    vehicleRegNumber: 'KDD 456Y',
    driverName: 'Peter Kamau',
    saccoId: 'sacco_metrolink',
    type: 'overspeeding',
    severity: 'medium',
    message: 'Speed advisory: Recorded 86 km/h on Thika Superhighway (Limit: 80 km/h).',
    latitude: -1.2215,
    longitude: 36.8821,
    speedKmH: 86,
    timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    status: 'active',
  },
];

export const MOCK_TRIPS: Trip[] = [
  {
    id: 'trip_demo_101',
    tripId: 'trip_demo_101',
    vehicleRegNumber: 'KBZ 819M',
    plateNumber: 'KBZ 819M',
    saccoId: 'sacco_2nk',
    saccoName: '2NK Sacco',
    routeName: 'Nairobi ➔ Nakuru Highway',
    origin: 'Nairobi Central Terminal',
    destination: 'Nakuru Town',
    status: 'active',
    currentSpeedKmH: 74,
    maxSpeedKmH: 78,
    avgSpeedKmH: 68,
    driverName: 'John Mwangi',
    passengerCount: 14,
    startTime: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    overspeedEventsCount: 0,
    violationsCount: 0,
  },
  {
    id: 'trip_demo_102',
    tripId: 'trip_demo_102',
    vehicleRegNumber: 'KCA 123X',
    plateNumber: 'KCA 123X',
    saccoId: 'sacco_metro',
    saccoName: 'Super Metro SACCO',
    routeName: 'CBD ➔ Juja Express',
    origin: 'Nairobi Archives',
    destination: 'Juja Flyover',
    status: 'active',
    currentSpeedKmH: 62,
    maxSpeedKmH: 76,
    avgSpeedKmH: 58,
    driverName: 'Kiprono Koech',
    passengerCount: 33,
    startTime: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    overspeedEventsCount: 0,
    violationsCount: 0,
  },
  {
    id: 'trip_demo_103',
    tripId: 'trip_demo_103',
    vehicleRegNumber: 'KDB 789Z',
    plateNumber: 'KDB 789Z',
    saccoId: 'sacco_greenline',
    saccoName: 'GreenLine SACCO',
    routeName: 'Nakuru ➔ Eldoret',
    origin: 'Nakuru Stage',
    destination: 'Eldoret CBD',
    status: 'completed',
    currentSpeedKmH: 0,
    maxSpeedKmH: 80,
    avgSpeedKmH: 71,
    driverName: 'Samuel Ochieng',
    passengerCount: 14,
    startTime: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    durationSeconds: 9000,
    distanceMeters: 142000,
    overspeedEventsCount: 0,
    violationsCount: 0,
  },
];

export const MOCK_DRIVERS: Driver[] = [
  {
    id: 'driver_001',
    name: 'John Mwangi',
    licenseNumber: 'DL-KEN-88192',
    saccoId: 'sacco_2nk',
    assignedVehicleReg: 'KBZ 819M',
    routeName: 'Nairobi - Nakuru',
    status: 'active',
    safetyScore: 98,
    phone: '+254 712 111 222',
    totalTrips: 412,
    totalViolations: 1,
  },
  {
    id: 'driver_002',
    name: 'Kiprono Koech',
    licenseNumber: 'DL-KEN-44012',
    saccoId: 'sacco_metro',
    assignedVehicleReg: 'KCA 123X',
    routeName: 'CBD - Juja',
    status: 'active',
    safetyScore: 96,
    phone: '+254 722 333 444',
    totalTrips: 620,
    totalViolations: 0,
  },
  {
    id: 'driver_003',
    name: 'Peter Kamau',
    licenseNumber: 'DL-KEN-99120',
    saccoId: 'sacco_metrolink',
    assignedVehicleReg: 'KDD 456Y',
    routeName: 'Nairobi - Thika',
    status: 'active',
    safetyScore: 84,
    phone: '+254 733 555 666',
    totalTrips: 340,
    totalViolations: 4,
  },
];

export const MOCK_VIOLATIONS: Violation[] = [
  {
    id: 'viol_001',
    violationId: 'viol_001',
    saccoId: 'sacco_metrolink',
    vehicleRegNumber: 'KDD 456Y',
    driverName: 'Peter Kamau',
    routeName: 'Thika Superhighway',
    recordedSpeedKmH: 88,
    speedLimitKmH: 80,
    severity: 'medium',
    confidenceScore: 94,
    isCorroborated: true,
    timestamp: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    status: 'pending',
    locationName: 'Ruiru Interchange',
  },
];

export const MOCK_COMPLAINTS: Complaint[] = [
  {
    id: 'comp_001',
    saccoId: 'sacco_2nk',
    vehicleRegNumber: 'KCC 512F',
    passengerName: 'Grace Wanjiku',
    title: 'Loud music & aggressive overtaking',
    description: 'Vehicle was overtaking on blind corners along Karatina bypass. Driver disregarded passenger requests.',
    status: 'investigating',
    createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit_001',
    saccoId: 'sacco_2nk',
    actorName: 'System Engine',
    actorRole: 'system',
    action: 'SPEED_GOVERNOR_SYNC',
    target: 'KBZ 819M',
    timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'audit_002',
    saccoId: 'sacco_metro',
    actorName: 'NTSA Officer Otieno',
    actorRole: 'authority',
    action: 'INSPECTION_PASSED',
    target: 'KCA 123X',
    timestamp: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
  },
];

export const MOCK_TEAM_USERS: TeamUser[] = [
  {
    id: 'team_001',
    saccoId: 'sacco_2nk',
    name: 'Samuel Ndung’u',
    email: 'ops@2nksacco.co.ke',
    role: 'sacco_manager',
    status: 'active',
  },
];

export const MOCK_INSPECTIONS: InspectionReport[] = [
  {
    id: 'insp_001',
    vehicleRegNumber: 'KBZ 819M',
    saccoId: 'sacco_2nk',
    saccoName: '2NK Sacco',
    inspectorId: 'insp_ntsa_01',
    inspectorName: 'Inspector Otieno',
    county: 'Nairobi',
    inspectionDate: '2026-03-01',
    speedGovernorStatus: 'valid',
    brakeStatus: 'pass',
    tireStatus: 'pass',
    overallResult: 'passed',
    certificateNumber: 'NTSA-CERT-2026-8819',
    expiryDate: '2027-03-01',
    notes: 'Fully compliant with PSV safety regulations. Digital speed limiter verified.',
    createdAt: new Date(Date.now() - 10 * 86400 * 1000).toISOString(),
  },
  {
    id: 'insp_002',
    vehicleRegNumber: 'KCA 123X',
    saccoId: 'sacco_metro',
    saccoName: 'Super Metro SACCO',
    inspectorId: 'insp_ntsa_02',
    inspectorName: 'Inspector Kariuki',
    county: 'Kiambu',
    inspectionDate: '2026-02-15',
    speedGovernorStatus: 'valid',
    brakeStatus: 'pass',
    tireStatus: 'pass',
    overallResult: 'passed',
    certificateNumber: 'NTSA-CERT-2026-4412',
    expiryDate: '2027-02-15',
    notes: 'Emergency exit clear, fire extinguisher calibrated.',
    createdAt: new Date(Date.now() - 25 * 86400 * 1000).toISOString(),
  },
];

export const MOCK_ANALYTICS: PlatformAnalyticsDaily = {
  id: 'platform_today',
  date: new Date().toISOString().slice(0, 10),
  type: 'platform_daily',
  totalTrips: 18420,
  totalViolations: 34,
  activeAlerts: 3,
  riskDistribution: {
    low: 82,
    medium: 14,
    high: 3,
    critical: 1,
  },
  userCount: 42100,
  saccoCount: 48,
  auditLogCount: 1250,
  complaintCount: 12,
  updatedAt: new Date().toISOString(),
};
